version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  minikube: ccpgames/minikube@0.0.1
jobs:
  build_container_and_push:
    executor: docker/publish
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: build app server container and tag
          command: |
            docker build -t flask-kubernetes .
            docker tag flask-kubernetes ${DOCKER_USERNAME}/flask-kubernetes:1.0
      - run:
          name: authenticate and push image to docker hub
          command: |
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            docker push ${DOCKER_USERNAME}/flask-kubernetes:1.0

  run_minikube_cluster:
    executor: minikube
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: Configure Minikube
          command: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
            sudo dpkg -i minikube_latest_amd64.deb
            minikube start --vm-driver=docker --kubernetes-version=v1.19.0
            minikube addons enable registry
      - run:
          name: Check status
          command: |
            minikube status
      - run:
          name: Check configure
          command: |
            cat ~/.kube/config
      - run:
          name: install dependencies
          command: |
            sudo snap install kubectl --classic
            kubectl version --client
      - run:
          name: Minikube cluster configure
          command: |
            #kubectl config view > kubectl.conf
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            kubectl apply -f deployment.yaml
      - run:
          name: Minikube cluster configure
          command: |
            kubectl get pods -A

commit: &only_commit
  filters:
    branches:
      only:
        - /add.*/

only_on_main_branch: &only_on_main_branch
  filters:
    branches:
      only: main

workflows:
  version: 2
  minikube-example:
    jobs:
      - run_minikube_cluster:
          context: circleci_test_app
          <<: *only_commit
          environment: dev

      - build_container_and_push:
          context: circleci_test_app
          <<: *only_commit
          environment: dev
          requires:
            - build_container_and_push

#workflows:
#  version: 2.1
#  build_container_app:
#    jobs:
#      - build_container_and_push:
#          environment: dev
#          context: circleci_test_app
#          <<: *only_commit
#
#  deploy_containber_app_dev:
#    jobs:
#      - build_container_and_push:
#          environment: dev
#          context: circleci_test_app
#          <<: *only_on_main_branch
#      - run_minikube_cluster_and_deploy_app:
#          environment: dev
#          context: circleci_test_app
#          <<: *only_on_main_branch
#          requires:
#            - build_container_and_push