version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
#  build_container_and_push:
#    executor: docker/publish
#    parameters:
#      environment:
#        type: string
#    steps:
#      - checkout
#      - attache_workspace:
#          at: ~/project
#      - run:
#          name: build app server container and tag
#          command: |
#            docker build -t flask-kubernetes .
#            docker tag flask-kubernetes ${DOCKER_USERNAME}/flask-kubernetes:1.0
#      - run:
#          name: authenticate and push image to docker hub
#          commad: |
#            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
#            docker push ${DOCKER_USERNAME}/flask-kubernetes:1.0

  run_minikube_cluster:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Configure Minikube
          command: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
            sudo dpkg -i minikube_latest_amd64.deb
            minikube start --vm-driver=docker --kubernetes-version=v1.19.0
            minikube addons enable registry
      - run:
          name: Check status
          command: |
            minikube status
      - run:
          name: install dependencies
          command: |
            snap install kubectl --classic
            kubectl version --client
#            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/v1.26.0)/bin/linux/amd64/kubectl"
#            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/v1.26.0)/bin/linux/amd64/kubectl.sha256"
#            chmod +x kubectl
#            mkdir -p ~/.local/bin
#            mv ./kubectl ~/.local/bin/kubectl
#            PATH=$PATH:~/.local/bin
#            install kubectl /usr/local/bin/kubectl
      - run:
          name: Minikube cluster configure
          command: |
            #kubectl config view > kubectl.conf
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            kubectl apply -f deployment.yaml


#  run_minikube_cluster_and_deploy_app:
#    executor: arm64
#    parameters:
#      environment:
#        type: string
#    steps:
#      - checkout
#      - attache_workspace:
#          at: ~/project
#      - run:
#          name: authenticate and pull image from docker hub
#          command: |
#            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
#            sudo dpkg -i minikube_latest_amd64.deb
#            minikube start --vm-driver=docker --kubernetes-version=v1.19.0
#      - run:
#          name: Minikube cluster configure
#          command: |
#            #kubectl config view > kubectl.conf
#            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
#            kubectl apply -f deployment.yaml

commit: &only_commit
  filters:
    branches:
      only:
        - /add.*/

only_on_main_branch: &only_on_main_branch
  filters:
    branches:
      only: main

workflows:
  version: 2
  minikube-example:
    jobs:
      - run_minikube_cluster:
          context: circleci_test_app
          <<: *only_commit

#workflows:
#  version: 2.1
#  build_container_app:
#    jobs:
#      - build_container_and_push:
#          environment: dev
#          context: circleci_test_app
#          <<: *only_commit
#
#  deploy_containber_app_dev:
#    jobs:
#      - build_container_and_push:
#          environment: dev
#          context: circleci_test_app
#          <<: *only_on_main_branch
#      - run_minikube_cluster_and_deploy_app:
#          environment: dev
#          context: circleci_test_app
#          <<: *only_on_main_branch
#          requires:
#            - build_container_and_push